wandb_version: 1

env_id:
  desc: null
  value: CartPole-v1
exp_name:
  desc: null
  value: Cart Pole (DQN)
seed:
  desc: null
  value: 500
num_envs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0005
buffer_size:
  desc: null
  value: 10000
batch_size:
  desc: null
  value: 64
train_frequency:
  desc: null
  value: 4
target_network_frequency:
  desc: null
  value: 30
gamma:
  desc: null
  value: 0.99
tau:
  desc: null
  value: 0.005
start_e:
  desc: null
  value: 0.9
end_e:
  desc: null
  value: 0.05
exploration_fraction:
  desc: null
  value: 0.15
total_timesteps:
  desc: null
  value: 600
learning_starts:
  desc: null
  value: 100
save_model:
  desc: null
  value: false
upload_model:
  desc: null
  value: false
wandb_project_name:
  desc: null
  value: Cart Pole
wandb_entity:
  desc: null
  value: null
track:
  desc: null
  value: true
cuda:
  desc: null
  value: true
torch_deterministic:
  desc: null
  value: true
capture_video:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    code_path: code/cart pole/cart_pole.py
    python_version: 3.11.7
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1704854779.295806
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.11.7
      5: 0.16.1
      8:
      - 3
      - 5
      13: windows-amd64
